(use-modules (opencog)
             (opencog cogserver)
             (opencog logger)
             (opencog nlp)
             (opencog nlp relex2logic)
             (opencog openpsi)
             (opencog attention)
             (opencog eva-behavior)
             (opencog ghost)
             (opencog ghost procedures)
             (opencog exec))


(load "load-actions.scm")

(ecan-based-ghost-rules #t)
(set-relex-server-host)

(start-cogserver "opencog.conf")
(cog-logger-set-stdout! #f)

(StateLink
  (ConceptNode "HEBBIAN_MAX_ALLOCATION_PERCENTAGE")
  (NumberNode "1.000000")
)

(StateLink 
   (ConceptNode "SPREADING_FILTER")
   (MemberLink
      (TypeNode "Value" )
      (TypeNode "FloatValue" )
      (TypeNode "StringValue" )
      (TypeNode "LinkValue" )
      (TypeNode "Valuation" )
      (TypeNode "TruthValue" )
      (TypeNode "SimpleTruthValue" )
      (TypeNode "CountTruthValue" )
      (TypeNode "IndefiniteTruthValue" )
      (TypeNode "FuzzyTruthValue" )
      (TypeNode "ProbabilisticTruthValue" )
      (TypeNode "EvidenceCountTruthValue" )
      (TypeNode "AttentionValue" )
      (TypeNode "Atom" )
      (TypeNode "Node" )
      (TypeNode "Link" )
      (TypeNode "NumberNode" )
      (TypeNode "OrderedLink" )
      (TypeNode "UnorderedLink" )
      (TypeNode "EvaluatableLink" )
      (TypeNode "BooleanLink" )
      (TypeNode "NumericLink" )
      (TypeNode "NumericOutputLink" )
      (TypeNode "TypeLink" )
      (TypeNode "TypeOutputLink" )
      (TypeNode "SetLink" )
      (TypeNode "ListLink" )
      (TypeNode "MemberLink" )
      (TypeNode "ContextLink" )
      (TypeNode "InheritanceLink" )
      (TypeNode "SubsetLink" )
      (TypeNode "IntensionalInheritanceLink" )
      (TypeNode "SimilarityLink" )
      (TypeNode "ExtensionalSimilarityLink" )
      (TypeNode "IntensionalSimilarityLink" )
      (TypeNode "TrueLink" )
      (TypeNode "FalseLink" )
      (TypeNode "AndLink" )
      (TypeNode "OrLink" )
      (TypeNode "NotLink" )
      (TypeNode "SequentialAndLink" )
      (TypeNode "SequentialOrLink" )
      (TypeNode "ChoiceLink" )
      (TypeNode "PresentLink" )
      (TypeNode "AbsentLink" )
      (TypeNode "ParallelLink" )
      (TypeNode "JoinLink" )
      (TypeNode "VariableNode" )
      (TypeNode "VariableList" )
      (TypeNode "GlobNode" )
      (TypeNode "QuoteLink" )
      (TypeNode "UnquoteLink" )
      (TypeNode "LocalQuoteLink" )
      (TypeNode "DontExecLink" )
      (TypeNode "FreeLink" )
      (TypeNode "DeleteLink" )
      (TypeNode "UniqueLink" )
      (TypeNode "StateLink" )
      (TypeNode "DefineLink" )
      (TypeNode "ScopeLink" )
      (TypeNode "RewriteLink" )
      (TypeNode "PrenexLink" )
      (TypeNode "LambdaLink" )
      (TypeNode "PutLink" )
      (TypeNode "PatternLink" )
      (TypeNode "SatisfactionLink" )
      (TypeNode "SatisfyingLink" )
      (TypeNode "GetLink" )
      (TypeNode "BindLink" )
      (TypeNode "DualLink" )
      (TypeNode "ForAllLink" )
      (TypeNode "ExistsLink" )
      (TypeNode "SatisfyingSetScopeLink" )
      (TypeNode "SatisfyingSetLink" )
      (TypeNode "ImplicationScopeLink" )
      (TypeNode "IntensionalImplicationScopeLink" )
      (TypeNode "ExtensionalImplicationScopeLink" )
      (TypeNode "EquivalenceScopeLink" )
      (TypeNode "IntensionalEquivalenceScopeLink" )
      (TypeNode "ExtensionalEquivalenceScopeLink" )
      (TypeNode "IntensionalImplicationLink" )
      (TypeNode "ExtensionalImplicationLink" )
      (TypeNode "EquivalenceLink" )
      (TypeNode "IntensionalEquivalenceLink" )
      (TypeNode "ExtensionalEquivalenceLink" )
      (TypeNode "AssociativeLink" )
      (TypeNode "AttractionLink" )
      (TypeNode "ExecutionLink" )
      (TypeNode "ProcedureNode" )
      (TypeNode "GroundedProcedureNode" )
      (TypeNode "SchemaNode" )
      (TypeNode "DefinedSchemaNode" )
      (TypeNode "GroundedSchemaNode" )
      (TypeNode "DefinedPredicateNode" )
      (TypeNode "GroundedPredicateNode" )
      (TypeNode "TypeNode" )
      (TypeNode "TypeInhNode" )
      (TypeNode "TypeCoInhNode" )
      (TypeNode "DefinedTypeNode" )
      (TypeNode "TypeChoice" )
      (TypeNode "TypeSetLink" )
      (TypeNode "ArrowLink" )
      (TypeNode "SignatureLink" )
      (TypeNode "FuzzyLink" )
      (TypeNode "TypedVariableLink" )
      (TypeNode "TypedAtomLink" )
      (TypeNode "AnchorNode" )
      (TypeNode "IntervalLink" )
      (TypeNode "QuantityLink" )
      (TypeNode "VirtualLink" )
      (TypeNode "GreaterThanLink" )
      (TypeNode "IdenticalLink" )
      (TypeNode "EqualLink" )
      (TypeNode "FunctionLink" )
      (TypeNode "ExecutionOutputLink" )
      (TypeNode "FoldLink" )
      (TypeNode "ArithmeticLink" )
      (TypeNode "PlusLink" )
      (TypeNode "MinusLink" )
      (TypeNode "TimesLink" )
      (TypeNode "DivideLink" )
      (TypeNode "RandomNumberLink" )
      (TypeNode "ArityLink" )
      (TypeNode "RandomChoiceLink" )
      (TypeNode "TimeLink" )
      (TypeNode "SleepLink" )
      (TypeNode "MapLink" )
      (TypeNode "ComposeLink" )
      (TypeNode "ProjectLink" )
      (TypeNode "Connector" )
      (TypeNode "ConnectorDir" )
      (TypeNode "ConnectorSeq" )
      (TypeNode "Section" )
      (TypeNode "HebbianLink" )
      (TypeNode "SymmetricHebbianLink" )
      (TypeNode "InverseHebbianLink" )
      (TypeNode "SymmetricInverseHebbianLink" )
      (TypeNode "SpaceMapNode" )
      (TypeNode "ObjectNode" )
      (TypeNode "BlockEntityNode" )
      (TypeNode "EntityNode" )
      (TypeNode "StructureNode" )
      (TypeNode "ImaginaryStructureNode" )
      (TypeNode "AtLocationLink" )
      (TypeNode "TimeNode" )
      (TypeNode "TimeIntervalLink" )
      (TypeNode "TimeDomainNode" )
      (TypeNode "AtTimeLink" )
      (TypeNode "LatestLink" )
      (TypeNode "BeforeLink" )
      (TypeNode "OverlapsLink" )
      (TypeNode "DuringLink" )
      (TypeNode "MeetsLink" )
      (TypeNode "StartsLink" )
      (TypeNode "FinishesLink" )
      (TypeNode "EqualsLink" )
      (TypeNode "AfterLink" )
      (TypeNode "OverlappedByLink" )
      (TypeNode "ContainsLink" )
      (TypeNode "MetByLink" )
      (TypeNode "StartedByLink" )
      (TypeNode "FinishedByLink" )
      (TypeNode "PredictiveImplicationLink" )
      (TypeNode "TailPredictiveImplicationLink" )
      (TypeNode "PredictiveAttractionLink" )
      (TypeNode "SimultaneousAndLink" )
      (TypeNode "EventualSequentialAND" )
      (TypeNode "EventualSequentialImplication" )
      (TypeNode "AnyNode" )
      (TypeNode "WordClassNode" )
      (TypeNode "ReferenceLink" )
      (TypeNode "ActionLink" )
      (TypeNode "DocumentNode" )
      (TypeNode "SentenceNode" )
      (TypeNode "SentenceLink" )
      (TypeNode "ParseNode" )
      (TypeNode "ParseLink" )
      (TypeNode "WordInstanceNode")
      (TypeNode "WordInstanceLink" )
      (TypeNode "UtteranceNode" )
      (TypeNode "DialogNode" )
      (TypeNode "PhraseNode" )
      (TypeNode "SequenceLink" )
      (TypeNode "WordSequenceLink" )
      (TypeNode "SentenceSequenceLink" )
      (TypeNode "DocumentSequenceLink" )
      (TypeNode "FeatureNode" )
      (TypeNode "FeatureLink" )
      (TypeNode "LinkGrammarRelationshipNode" )
      (TypeNode "DefinedLinguisticConceptNode" )
      (TypeNode "DefinedLinguisticPredicateNode" )
      (TypeNode "DefinedLinguisticRelationshipNode" )
      (TypeNode "PrepositionalRelationshipNode" )
      (TypeNode "WordSenseNode" )
      (TypeNode "WordSenseLink" )
      (TypeNode "PartOfSpeechNode" )
      (TypeNode "PartOfSpeechLink" )
      (TypeNode "LemmaNode" )
      (TypeNode "LemmaLink" )
      (TypeNode "HolonymLink" )
      (TypeNode "TenseNode" )
      (TypeNode "TenseLink" )
      (TypeNode "CosenseLink" )
      (TypeNode "SemeNode" )
      (TypeNode "SemanticRelationNode" )
      (TypeNode "InterpretationNode" )
      (TypeNode "InterpretationLink" )
      (TypeNode "SpecificEntityNode" )
      (TypeNode "LgDictNode" )
      (TypeNode "LgDictEntry" )
      (TypeNode "LgParseLink" )
      (TypeNode "LgParseMinimal" )
      (TypeNode "LgConnectorNode" )
      (TypeNode "LgConnMultiNode" )
      (TypeNode "LgConnDirNode" )
      (TypeNode "LgConnector" )
      (TypeNode "LgSeq" )
      (TypeNode "LgAnd" )
      (TypeNode "LgOr" )
      (TypeNode "LgWordCset" )
      (TypeNode "LgDisjunct" )
      (TypeNode "LgLinkInstanceNode" )
      (TypeNode "LgLinkInstanceLink" )
      (TypeNode "SetTypeLink" )
      (TypeNode "SetSizeLink")
   )
)


; load and start the ghost-bridge-action-node
(use-modules (opencog ghost-bridge-action-node))
(start-ghost-bridge-action-node)

; Start the ghost loop
(ghost-run)
